[package]
name = "i2c-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i2c-linux = { version = "0.1.2", features = ["i2c"] }
